[2022-06-13 12:45:59,484] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_fhvhv_tripdata_partitioned_table_task scheduled__2022-06-12T00:00:00+00:00 [queued]>
[2022-06-13 12:45:59,501] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_fhvhv_tripdata_partitioned_table_task scheduled__2022-06-12T00:00:00+00:00 [queued]>
[2022-06-13 12:45:59,503] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 12:45:59,505] {taskinstance.py:1358} INFO - Starting attempt 9 of 10
[2022-06-13 12:45:59,506] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 12:45:59,525] {taskinstance.py:1378} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_fhvhv_tripdata_partitioned_table_task> on 2022-06-12 00:00:00+00:00
[2022-06-13 12:45:59,543] {standard_task_runner.py:52} INFO - Started process 15214 to run task
[2022-06-13 12:45:59,549] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_create_fhvhv_tripdata_partitioned_table_task', 'scheduled__2022-06-12T00:00:00+00:00', '--job-id', '657', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag.py', '--cfg-path', '/tmp/tmponvk_lf3', '--error-file', '/tmp/tmpik739ahq']
[2022-06-13 12:45:59,553] {standard_task_runner.py:80} INFO - Job 657: Subtask bq_create_fhvhv_tripdata_partitioned_table_task
[2022-06-13 12:45:59,638] {task_command.py:370} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_create_fhvhv_tripdata_partitioned_table_task scheduled__2022-06-12T00:00:00+00:00 [running]> on host 0825143a1170
[2022-06-13 12:45:59,715] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_create_fhvhv_tripdata_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-12T00:00:00+00:00
[2022-06-13 12:45:59,720] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-06-13 12:45:59,722] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-06-13 12:45:59,727] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-13 12:45:59,730] {bigquery.py:2148} INFO - Executing: {'query': {'query': {'CREATE OR REPLACE TABLE trips_data_all.fhv_trips             (             hvfhs_license_num STRING,             dispatching_base_num STRING,             originating_base_num STRING,             request_datetime TIMESTAMP,             on_scene_datetime TIMESTAMP,             pickup_datetime TIMESTAMP,             dropoff_datetime TIMESTAMP,             PULocationID INT64,             DOLocationID INT64,             trip_miles FLOAT64,             trip_time INT64,             base_passenger_fare FLOAT64,             tolls FLOAT64,             bcf FLOAT64,             sales_tax FLOAT64,             congestion_surcharge FLOAT64,             airport_fee INT64,             tips FLOAT64,             driver_pay FLOAT64,             shared_request_flag STRING,             shared_match_flag STRING,             access_a_ride_flag STRING,             wav_request_flag STRING,             wav_match_flag STRING             )     PARTITION BY DATE(pickup_datetime)     OPTIONS(     partition_expiration_days=10000     )     AS (         SELECT              *         REPLACE(NULL AS airport_fee)         FROM              trips_data_all.fhvhv_tripdata_external_table     );'}, 'useLegacySql': False}}
[2022-06-13 12:45:59,742] {bigquery.py:1538} INFO - Inserting job ***_gcs_2_bq_dag_bq_create_fhvhv_tripdata_partitioned_table_task_2022_06_12T00_00_00_00_00_0ce7da01a1c0addf0018ad4d7fb46019
[2022-06-13 12:45:59,747] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2149, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2114, in _submit_job
    retry=self.result_retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1544, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 725, in result
    self._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1298, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 518, in _begin
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 479, in api_request
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
[2022-06-13 12:45:59,765] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_dag, task_id=bq_create_fhvhv_tripdata_partitioned_table_task, execution_date=20220612T000000, start_date=20220613T124559, end_date=20220613T124559
[2022-06-13 12:45:59,782] {standard_task_runner.py:97} ERROR - Failed to execute job 657 for task bq_create_fhvhv_tripdata_partitioned_table_task (Object of type set is not JSON serializable; 15214)
[2022-06-13 12:45:59,804] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-13 12:45:59,890] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
